mysql:
  dns: root:ywh666@tcp(47.117.125.6:3306)/ginchat?charset=utf8&parseTime=True&loc=Local
redis:
  addr: "47.117.125.6:6379"
  password: ""
  DB: 0
  poolSize: 30
  miniIdleConn: 30
oss:
  Endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
  AccessKeyId: "LTAI5tJXa37nNG3aqWfrreC2"
  AccessKeySecret: "T2LiBvRVCvQfb3l3gvAVFOfYPBBKnl"
  Bucket: "easychat-fish"
timeout:
  DelayHeartbeat: 5 # 10      # 心跳检测定时器初次检测时间 单位秒
  HeartbeatHz: 5 # 30         # 心跳检测定时器重置时间 单位秒
  HeartbeatMaxTime: 10 # 10800 # 判断连接是否应该断开的最大阈值时间 单位秒
  RedisOnlineTime: 4      # 缓存的在线用户时长 单位小时

port:
  server: ":8082"
  udp: 3001